GET http://0.0.0.0:8055/roles HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImViOGNkMjk2LTlkZDQtNGM0My05OGExLWI0OTZhZmYxMjNlNCIsInJvbGUiOiJlMmE1YmRlMi0wOWFiLTQ0ZTQtODY2OS1jOWRjMzRjMTU3ZTUiLCJhcHBfYWNjZXNzIjoxLCJhZG1pbl9hY2Nlc3MiOjEsImlhdCI6MTY4MTIyODkwMCwiZXhwIjoxNjgxMjI5ODAwLCJpc3MiOiJkaXJlY3R1cyJ9.3WMRi2j187wb9KLloudhk4fcI_GVKmvBeEXV4xqTXCw