GET http://0.0.0.0:8055/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIyNjQ4M2MzLTk3NWItNDgxNi04ZTFhLWFmNDk5M2YwZGRlNyIsInJvbGUiOiJlMmE1YmRlMi0wOWFiLTQ0ZTQtODY2OS1jOWRjMzRjMTU3ZTUiLCJhcHBfYWNjZXNzIjoxLCJhZG1pbl9hY2Nlc3MiOjEsImlhdCI6MTY4MDg3ODk3NCwiZXhwIjoxNjgwODc5ODc0LCJpc3MiOiJkaXJlY3R1cyJ9.nAbRMwx27ksA2JyaN06Q3Bi116PKwUNbnu2G8GpHWCk